/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as Char123LocaleChar125RouteRouteImport } from './routes/{-$locale}/route'
import { Route as Char123LocaleChar125PublicRouteRouteImport } from './routes/{-$locale}/_public/route'
import { Route as Char123LocaleChar125GuestRouteRouteImport } from './routes/{-$locale}/_guest/route'
import { Route as Char123LocaleChar125AppRouteRouteImport } from './routes/{-$locale}/_app/route'
import { Route as Char123LocaleChar125PublicIndexRouteImport } from './routes/{-$locale}/_public/index'
import { Route as Char123LocaleChar125PublicTermsOfServiceRouteImport } from './routes/{-$locale}/_public/terms-of-service'
import { Route as Char123LocaleChar125PublicPrivacyPolicyRouteImport } from './routes/{-$locale}/_public/privacy-policy'
import { Route as Char123LocaleChar125PublicPlaygroundRouteImport } from './routes/{-$locale}/_public/playground'
import { Route as Char123LocaleChar125PublicHomeRouteImport } from './routes/{-$locale}/_public/home'
import { Route as Char123LocaleChar125PublicErrorRouteImport } from './routes/{-$locale}/_public/error'
import { Route as Char123LocaleChar125GuestSignupRouteImport } from './routes/{-$locale}/_guest/signup'
import { Route as Char123LocaleChar125GuestLoginRouteImport } from './routes/{-$locale}/_guest/login'
import { Route as ApiHealthLiveRouteImport } from './routes/[_]api/health/live'
import { Route as Char123LocaleChar125AppOrgSlugRouteRouteImport } from './routes/{-$locale}/_app/$orgSlug/route'
import { Route as Char123LocaleChar125AppOrganizationsNewRouteImport } from './routes/{-$locale}/_app/organizations/new'
import { Route as Char123LocaleChar125AppOrgSlugOnboardingRouteImport } from './routes/{-$locale}/_app/$orgSlug/onboarding'
import { Route as Char123LocaleChar125AppOrgSlugShellRouteRouteImport } from './routes/{-$locale}/_app/$orgSlug/_shell/route'
import { Route as Char123LocaleChar125AppOrgSlugShellIndexRouteImport } from './routes/{-$locale}/_app/$orgSlug/_shell/index'
import { Route as Char123LocaleChar125AppOrgSlugShellSettingsIndexRouteImport } from './routes/{-$locale}/_app/$orgSlug/_shell/settings/index'
import { Route as Char123LocaleChar125AppOrgSlugShellSalesIndexRouteImport } from './routes/{-$locale}/_app/$orgSlug/_shell/sales/index'
import { Route as Char123LocaleChar125AppOrgSlugShellPurchaseIndexRouteImport } from './routes/{-$locale}/_app/$orgSlug/_shell/purchase/index'
import { Route as Char123LocaleChar125AppOrgSlugShellSettingsChartOfAccountsRouteImport } from './routes/{-$locale}/_app/$orgSlug/_shell/settings/chart-of-accounts'
import { Route as Char123LocaleChar125AppOrgSlugShellSettingsBusinessRouteImport } from './routes/{-$locale}/_app/$orgSlug/_shell/settings/business'
import { Route as Char123LocaleChar125AppOrgSlugShellSettingsAccountingPeriodsRouteImport } from './routes/{-$locale}/_app/$orgSlug/_shell/settings/accounting-periods'
import { Route as Char123LocaleChar125AppOrgSlugShellReportsTrialBalanceRouteImport } from './routes/{-$locale}/_app/$orgSlug/_shell/reports/trial-balance'
import { Route as Char123LocaleChar125AppOrgSlugShellReportsGeneralLedgerRouteImport } from './routes/{-$locale}/_app/$orgSlug/_shell/reports/general-ledger'
import { Route as Char123LocaleChar125AppOrgSlugShellRecordsPartiesRouteImport } from './routes/{-$locale}/_app/$orgSlug/_shell/records/parties'
import { Route as Char123LocaleChar125AppOrgSlugShellRecordsItemsRouteImport } from './routes/{-$locale}/_app/$orgSlug/_shell/records/items'
import { Route as Char123LocaleChar125AppOrgSlugShellAccountingJournalEntriesRouteImport } from './routes/{-$locale}/_app/$orgSlug/_shell/accounting/journal-entries'
import { Route as Char123LocaleChar125AppOrgSlugShellSalesReceiptsIndexRouteImport } from './routes/{-$locale}/_app/$orgSlug/_shell/sales/receipts/index'
import { Route as Char123LocaleChar125AppOrgSlugShellSalesInvoicesIndexRouteImport } from './routes/{-$locale}/_app/$orgSlug/_shell/sales/invoices/index'
import { Route as Char123LocaleChar125AppOrgSlugShellPurchasePaymentsIndexRouteImport } from './routes/{-$locale}/_app/$orgSlug/_shell/purchase/payments/index'
import { Route as Char123LocaleChar125AppOrgSlugShellPurchaseBillsIndexRouteImport } from './routes/{-$locale}/_app/$orgSlug/_shell/purchase/bills/index'
import { Route as Char123LocaleChar125AppOrgSlugShellSalesReceiptsNewRouteImport } from './routes/{-$locale}/_app/$orgSlug/_shell/sales/receipts/new'
import { Route as Char123LocaleChar125AppOrgSlugShellSalesReceiptsDocumentIdRouteImport } from './routes/{-$locale}/_app/$orgSlug/_shell/sales/receipts/$documentId'
import { Route as Char123LocaleChar125AppOrgSlugShellSalesInvoicesNewRouteImport } from './routes/{-$locale}/_app/$orgSlug/_shell/sales/invoices/new'
import { Route as Char123LocaleChar125AppOrgSlugShellSalesInvoicesDocumentIdRouteImport } from './routes/{-$locale}/_app/$orgSlug/_shell/sales/invoices/$documentId'
import { Route as Char123LocaleChar125AppOrgSlugShellPurchasePaymentsNewRouteImport } from './routes/{-$locale}/_app/$orgSlug/_shell/purchase/payments/new'
import { Route as Char123LocaleChar125AppOrgSlugShellPurchasePaymentsDocumentIdRouteImport } from './routes/{-$locale}/_app/$orgSlug/_shell/purchase/payments/$documentId'
import { Route as Char123LocaleChar125AppOrgSlugShellPurchaseBillsNewRouteImport } from './routes/{-$locale}/_app/$orgSlug/_shell/purchase/bills/new'
import { Route as Char123LocaleChar125AppOrgSlugShellPurchaseBillsDocumentIdRouteImport } from './routes/{-$locale}/_app/$orgSlug/_shell/purchase/bills/$documentId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125RouteRoute =
  Char123LocaleChar125RouteRouteImport.update({
    id: '/{-$locale}',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125PublicRouteRoute =
  Char123LocaleChar125PublicRouteRouteImport.update({
    id: '/_public',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125GuestRouteRoute =
  Char123LocaleChar125GuestRouteRouteImport.update({
    id: '/_guest',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AppRouteRoute =
  Char123LocaleChar125AppRouteRouteImport.update({
    id: '/_app',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125PublicIndexRoute =
  Char123LocaleChar125PublicIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125PublicRouteRoute,
  } as any)
const Char123LocaleChar125PublicTermsOfServiceRoute =
  Char123LocaleChar125PublicTermsOfServiceRouteImport.update({
    id: '/terms-of-service',
    path: '/terms-of-service',
    getParentRoute: () => Char123LocaleChar125PublicRouteRoute,
  } as any)
const Char123LocaleChar125PublicPrivacyPolicyRoute =
  Char123LocaleChar125PublicPrivacyPolicyRouteImport.update({
    id: '/privacy-policy',
    path: '/privacy-policy',
    getParentRoute: () => Char123LocaleChar125PublicRouteRoute,
  } as any)
const Char123LocaleChar125PublicPlaygroundRoute =
  Char123LocaleChar125PublicPlaygroundRouteImport.update({
    id: '/playground',
    path: '/playground',
    getParentRoute: () => Char123LocaleChar125PublicRouteRoute,
  } as any)
const Char123LocaleChar125PublicHomeRoute =
  Char123LocaleChar125PublicHomeRouteImport.update({
    id: '/home',
    path: '/home',
    getParentRoute: () => Char123LocaleChar125PublicRouteRoute,
  } as any)
const Char123LocaleChar125PublicErrorRoute =
  Char123LocaleChar125PublicErrorRouteImport.update({
    id: '/error',
    path: '/error',
    getParentRoute: () => Char123LocaleChar125PublicRouteRoute,
  } as any)
const Char123LocaleChar125GuestSignupRoute =
  Char123LocaleChar125GuestSignupRouteImport.update({
    id: '/signup',
    path: '/signup',
    getParentRoute: () => Char123LocaleChar125GuestRouteRoute,
  } as any)
const Char123LocaleChar125GuestLoginRoute =
  Char123LocaleChar125GuestLoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => Char123LocaleChar125GuestRouteRoute,
  } as any)
const ApiHealthLiveRoute = ApiHealthLiveRouteImport.update({
  id: '/_api/health/live',
  path: '/_api/health/live',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125AppOrgSlugRouteRoute =
  Char123LocaleChar125AppOrgSlugRouteRouteImport.update({
    id: '/$orgSlug',
    path: '/$orgSlug',
    getParentRoute: () => Char123LocaleChar125AppRouteRoute,
  } as any)
const Char123LocaleChar125AppOrganizationsNewRoute =
  Char123LocaleChar125AppOrganizationsNewRouteImport.update({
    id: '/organizations/new',
    path: '/organizations/new',
    getParentRoute: () => Char123LocaleChar125AppRouteRoute,
  } as any)
const Char123LocaleChar125AppOrgSlugOnboardingRoute =
  Char123LocaleChar125AppOrgSlugOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => Char123LocaleChar125AppOrgSlugRouteRoute,
  } as any)
const Char123LocaleChar125AppOrgSlugShellRouteRoute =
  Char123LocaleChar125AppOrgSlugShellRouteRouteImport.update({
    id: '/_shell',
    getParentRoute: () => Char123LocaleChar125AppOrgSlugRouteRoute,
  } as any)
const Char123LocaleChar125AppOrgSlugShellIndexRoute =
  Char123LocaleChar125AppOrgSlugShellIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125AppOrgSlugShellRouteRoute,
  } as any)
const Char123LocaleChar125AppOrgSlugShellSettingsIndexRoute =
  Char123LocaleChar125AppOrgSlugShellSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => Char123LocaleChar125AppOrgSlugShellRouteRoute,
  } as any)
const Char123LocaleChar125AppOrgSlugShellSalesIndexRoute =
  Char123LocaleChar125AppOrgSlugShellSalesIndexRouteImport.update({
    id: '/sales/',
    path: '/sales/',
    getParentRoute: () => Char123LocaleChar125AppOrgSlugShellRouteRoute,
  } as any)
const Char123LocaleChar125AppOrgSlugShellPurchaseIndexRoute =
  Char123LocaleChar125AppOrgSlugShellPurchaseIndexRouteImport.update({
    id: '/purchase/',
    path: '/purchase/',
    getParentRoute: () => Char123LocaleChar125AppOrgSlugShellRouteRoute,
  } as any)
const Char123LocaleChar125AppOrgSlugShellSettingsChartOfAccountsRoute =
  Char123LocaleChar125AppOrgSlugShellSettingsChartOfAccountsRouteImport.update({
    id: '/settings/chart-of-accounts',
    path: '/settings/chart-of-accounts',
    getParentRoute: () => Char123LocaleChar125AppOrgSlugShellRouteRoute,
  } as any)
const Char123LocaleChar125AppOrgSlugShellSettingsBusinessRoute =
  Char123LocaleChar125AppOrgSlugShellSettingsBusinessRouteImport.update({
    id: '/settings/business',
    path: '/settings/business',
    getParentRoute: () => Char123LocaleChar125AppOrgSlugShellRouteRoute,
  } as any)
const Char123LocaleChar125AppOrgSlugShellSettingsAccountingPeriodsRoute =
  Char123LocaleChar125AppOrgSlugShellSettingsAccountingPeriodsRouteImport.update(
    {
      id: '/settings/accounting-periods',
      path: '/settings/accounting-periods',
      getParentRoute: () => Char123LocaleChar125AppOrgSlugShellRouteRoute,
    } as any,
  )
const Char123LocaleChar125AppOrgSlugShellReportsTrialBalanceRoute =
  Char123LocaleChar125AppOrgSlugShellReportsTrialBalanceRouteImport.update({
    id: '/reports/trial-balance',
    path: '/reports/trial-balance',
    getParentRoute: () => Char123LocaleChar125AppOrgSlugShellRouteRoute,
  } as any)
const Char123LocaleChar125AppOrgSlugShellReportsGeneralLedgerRoute =
  Char123LocaleChar125AppOrgSlugShellReportsGeneralLedgerRouteImport.update({
    id: '/reports/general-ledger',
    path: '/reports/general-ledger',
    getParentRoute: () => Char123LocaleChar125AppOrgSlugShellRouteRoute,
  } as any)
const Char123LocaleChar125AppOrgSlugShellRecordsPartiesRoute =
  Char123LocaleChar125AppOrgSlugShellRecordsPartiesRouteImport.update({
    id: '/records/parties',
    path: '/records/parties',
    getParentRoute: () => Char123LocaleChar125AppOrgSlugShellRouteRoute,
  } as any)
const Char123LocaleChar125AppOrgSlugShellRecordsItemsRoute =
  Char123LocaleChar125AppOrgSlugShellRecordsItemsRouteImport.update({
    id: '/records/items',
    path: '/records/items',
    getParentRoute: () => Char123LocaleChar125AppOrgSlugShellRouteRoute,
  } as any)
const Char123LocaleChar125AppOrgSlugShellAccountingJournalEntriesRoute =
  Char123LocaleChar125AppOrgSlugShellAccountingJournalEntriesRouteImport.update(
    {
      id: '/accounting/journal-entries',
      path: '/accounting/journal-entries',
      getParentRoute: () => Char123LocaleChar125AppOrgSlugShellRouteRoute,
    } as any,
  )
const Char123LocaleChar125AppOrgSlugShellSalesReceiptsIndexRoute =
  Char123LocaleChar125AppOrgSlugShellSalesReceiptsIndexRouteImport.update({
    id: '/sales/receipts/',
    path: '/sales/receipts/',
    getParentRoute: () => Char123LocaleChar125AppOrgSlugShellRouteRoute,
  } as any)
const Char123LocaleChar125AppOrgSlugShellSalesInvoicesIndexRoute =
  Char123LocaleChar125AppOrgSlugShellSalesInvoicesIndexRouteImport.update({
    id: '/sales/invoices/',
    path: '/sales/invoices/',
    getParentRoute: () => Char123LocaleChar125AppOrgSlugShellRouteRoute,
  } as any)
const Char123LocaleChar125AppOrgSlugShellPurchasePaymentsIndexRoute =
  Char123LocaleChar125AppOrgSlugShellPurchasePaymentsIndexRouteImport.update({
    id: '/purchase/payments/',
    path: '/purchase/payments/',
    getParentRoute: () => Char123LocaleChar125AppOrgSlugShellRouteRoute,
  } as any)
const Char123LocaleChar125AppOrgSlugShellPurchaseBillsIndexRoute =
  Char123LocaleChar125AppOrgSlugShellPurchaseBillsIndexRouteImport.update({
    id: '/purchase/bills/',
    path: '/purchase/bills/',
    getParentRoute: () => Char123LocaleChar125AppOrgSlugShellRouteRoute,
  } as any)
const Char123LocaleChar125AppOrgSlugShellSalesReceiptsNewRoute =
  Char123LocaleChar125AppOrgSlugShellSalesReceiptsNewRouteImport.update({
    id: '/sales/receipts/new',
    path: '/sales/receipts/new',
    getParentRoute: () => Char123LocaleChar125AppOrgSlugShellRouteRoute,
  } as any)
const Char123LocaleChar125AppOrgSlugShellSalesReceiptsDocumentIdRoute =
  Char123LocaleChar125AppOrgSlugShellSalesReceiptsDocumentIdRouteImport.update({
    id: '/sales/receipts/$documentId',
    path: '/sales/receipts/$documentId',
    getParentRoute: () => Char123LocaleChar125AppOrgSlugShellRouteRoute,
  } as any)
const Char123LocaleChar125AppOrgSlugShellSalesInvoicesNewRoute =
  Char123LocaleChar125AppOrgSlugShellSalesInvoicesNewRouteImport.update({
    id: '/sales/invoices/new',
    path: '/sales/invoices/new',
    getParentRoute: () => Char123LocaleChar125AppOrgSlugShellRouteRoute,
  } as any)
const Char123LocaleChar125AppOrgSlugShellSalesInvoicesDocumentIdRoute =
  Char123LocaleChar125AppOrgSlugShellSalesInvoicesDocumentIdRouteImport.update({
    id: '/sales/invoices/$documentId',
    path: '/sales/invoices/$documentId',
    getParentRoute: () => Char123LocaleChar125AppOrgSlugShellRouteRoute,
  } as any)
const Char123LocaleChar125AppOrgSlugShellPurchasePaymentsNewRoute =
  Char123LocaleChar125AppOrgSlugShellPurchasePaymentsNewRouteImport.update({
    id: '/purchase/payments/new',
    path: '/purchase/payments/new',
    getParentRoute: () => Char123LocaleChar125AppOrgSlugShellRouteRoute,
  } as any)
const Char123LocaleChar125AppOrgSlugShellPurchasePaymentsDocumentIdRoute =
  Char123LocaleChar125AppOrgSlugShellPurchasePaymentsDocumentIdRouteImport.update(
    {
      id: '/purchase/payments/$documentId',
      path: '/purchase/payments/$documentId',
      getParentRoute: () => Char123LocaleChar125AppOrgSlugShellRouteRoute,
    } as any,
  )
const Char123LocaleChar125AppOrgSlugShellPurchaseBillsNewRoute =
  Char123LocaleChar125AppOrgSlugShellPurchaseBillsNewRouteImport.update({
    id: '/purchase/bills/new',
    path: '/purchase/bills/new',
    getParentRoute: () => Char123LocaleChar125AppOrgSlugShellRouteRoute,
  } as any)
const Char123LocaleChar125AppOrgSlugShellPurchaseBillsDocumentIdRoute =
  Char123LocaleChar125AppOrgSlugShellPurchaseBillsDocumentIdRouteImport.update({
    id: '/purchase/bills/$documentId',
    path: '/purchase/bills/$documentId',
    getParentRoute: () => Char123LocaleChar125AppOrgSlugShellRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}/$orgSlug': typeof Char123LocaleChar125AppOrgSlugRouteRouteWithChildren
  '/_api/health/live': typeof ApiHealthLiveRoute
  '/{-$locale}/login': typeof Char123LocaleChar125GuestLoginRoute
  '/{-$locale}/signup': typeof Char123LocaleChar125GuestSignupRoute
  '/{-$locale}/error': typeof Char123LocaleChar125PublicErrorRoute
  '/{-$locale}/home': typeof Char123LocaleChar125PublicHomeRoute
  '/{-$locale}/playground': typeof Char123LocaleChar125PublicPlaygroundRoute
  '/{-$locale}/privacy-policy': typeof Char123LocaleChar125PublicPrivacyPolicyRoute
  '/{-$locale}/terms-of-service': typeof Char123LocaleChar125PublicTermsOfServiceRoute
  '/{-$locale}/': typeof Char123LocaleChar125PublicIndexRoute
  '/{-$locale}/$orgSlug/onboarding': typeof Char123LocaleChar125AppOrgSlugOnboardingRoute
  '/{-$locale}/organizations/new': typeof Char123LocaleChar125AppOrganizationsNewRoute
  '/{-$locale}/$orgSlug/': typeof Char123LocaleChar125AppOrgSlugShellIndexRoute
  '/{-$locale}/$orgSlug/accounting/journal-entries': typeof Char123LocaleChar125AppOrgSlugShellAccountingJournalEntriesRoute
  '/{-$locale}/$orgSlug/records/items': typeof Char123LocaleChar125AppOrgSlugShellRecordsItemsRoute
  '/{-$locale}/$orgSlug/records/parties': typeof Char123LocaleChar125AppOrgSlugShellRecordsPartiesRoute
  '/{-$locale}/$orgSlug/reports/general-ledger': typeof Char123LocaleChar125AppOrgSlugShellReportsGeneralLedgerRoute
  '/{-$locale}/$orgSlug/reports/trial-balance': typeof Char123LocaleChar125AppOrgSlugShellReportsTrialBalanceRoute
  '/{-$locale}/$orgSlug/settings/accounting-periods': typeof Char123LocaleChar125AppOrgSlugShellSettingsAccountingPeriodsRoute
  '/{-$locale}/$orgSlug/settings/business': typeof Char123LocaleChar125AppOrgSlugShellSettingsBusinessRoute
  '/{-$locale}/$orgSlug/settings/chart-of-accounts': typeof Char123LocaleChar125AppOrgSlugShellSettingsChartOfAccountsRoute
  '/{-$locale}/$orgSlug/purchase/': typeof Char123LocaleChar125AppOrgSlugShellPurchaseIndexRoute
  '/{-$locale}/$orgSlug/sales/': typeof Char123LocaleChar125AppOrgSlugShellSalesIndexRoute
  '/{-$locale}/$orgSlug/settings/': typeof Char123LocaleChar125AppOrgSlugShellSettingsIndexRoute
  '/{-$locale}/$orgSlug/purchase/bills/$documentId': typeof Char123LocaleChar125AppOrgSlugShellPurchaseBillsDocumentIdRoute
  '/{-$locale}/$orgSlug/purchase/bills/new': typeof Char123LocaleChar125AppOrgSlugShellPurchaseBillsNewRoute
  '/{-$locale}/$orgSlug/purchase/payments/$documentId': typeof Char123LocaleChar125AppOrgSlugShellPurchasePaymentsDocumentIdRoute
  '/{-$locale}/$orgSlug/purchase/payments/new': typeof Char123LocaleChar125AppOrgSlugShellPurchasePaymentsNewRoute
  '/{-$locale}/$orgSlug/sales/invoices/$documentId': typeof Char123LocaleChar125AppOrgSlugShellSalesInvoicesDocumentIdRoute
  '/{-$locale}/$orgSlug/sales/invoices/new': typeof Char123LocaleChar125AppOrgSlugShellSalesInvoicesNewRoute
  '/{-$locale}/$orgSlug/sales/receipts/$documentId': typeof Char123LocaleChar125AppOrgSlugShellSalesReceiptsDocumentIdRoute
  '/{-$locale}/$orgSlug/sales/receipts/new': typeof Char123LocaleChar125AppOrgSlugShellSalesReceiptsNewRoute
  '/{-$locale}/$orgSlug/purchase/bills/': typeof Char123LocaleChar125AppOrgSlugShellPurchaseBillsIndexRoute
  '/{-$locale}/$orgSlug/purchase/payments/': typeof Char123LocaleChar125AppOrgSlugShellPurchasePaymentsIndexRoute
  '/{-$locale}/$orgSlug/sales/invoices/': typeof Char123LocaleChar125AppOrgSlugShellSalesInvoicesIndexRoute
  '/{-$locale}/$orgSlug/sales/receipts/': typeof Char123LocaleChar125AppOrgSlugShellSalesReceiptsIndexRoute
}
export interface FileRoutesByTo {
  '/{-$locale}': typeof Char123LocaleChar125PublicIndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}/$orgSlug': typeof Char123LocaleChar125AppOrgSlugShellIndexRoute
  '/_api/health/live': typeof ApiHealthLiveRoute
  '/{-$locale}/login': typeof Char123LocaleChar125GuestLoginRoute
  '/{-$locale}/signup': typeof Char123LocaleChar125GuestSignupRoute
  '/{-$locale}/error': typeof Char123LocaleChar125PublicErrorRoute
  '/{-$locale}/home': typeof Char123LocaleChar125PublicHomeRoute
  '/{-$locale}/playground': typeof Char123LocaleChar125PublicPlaygroundRoute
  '/{-$locale}/privacy-policy': typeof Char123LocaleChar125PublicPrivacyPolicyRoute
  '/{-$locale}/terms-of-service': typeof Char123LocaleChar125PublicTermsOfServiceRoute
  '/{-$locale}/$orgSlug/onboarding': typeof Char123LocaleChar125AppOrgSlugOnboardingRoute
  '/{-$locale}/organizations/new': typeof Char123LocaleChar125AppOrganizationsNewRoute
  '/{-$locale}/$orgSlug/accounting/journal-entries': typeof Char123LocaleChar125AppOrgSlugShellAccountingJournalEntriesRoute
  '/{-$locale}/$orgSlug/records/items': typeof Char123LocaleChar125AppOrgSlugShellRecordsItemsRoute
  '/{-$locale}/$orgSlug/records/parties': typeof Char123LocaleChar125AppOrgSlugShellRecordsPartiesRoute
  '/{-$locale}/$orgSlug/reports/general-ledger': typeof Char123LocaleChar125AppOrgSlugShellReportsGeneralLedgerRoute
  '/{-$locale}/$orgSlug/reports/trial-balance': typeof Char123LocaleChar125AppOrgSlugShellReportsTrialBalanceRoute
  '/{-$locale}/$orgSlug/settings/accounting-periods': typeof Char123LocaleChar125AppOrgSlugShellSettingsAccountingPeriodsRoute
  '/{-$locale}/$orgSlug/settings/business': typeof Char123LocaleChar125AppOrgSlugShellSettingsBusinessRoute
  '/{-$locale}/$orgSlug/settings/chart-of-accounts': typeof Char123LocaleChar125AppOrgSlugShellSettingsChartOfAccountsRoute
  '/{-$locale}/$orgSlug/purchase': typeof Char123LocaleChar125AppOrgSlugShellPurchaseIndexRoute
  '/{-$locale}/$orgSlug/sales': typeof Char123LocaleChar125AppOrgSlugShellSalesIndexRoute
  '/{-$locale}/$orgSlug/settings': typeof Char123LocaleChar125AppOrgSlugShellSettingsIndexRoute
  '/{-$locale}/$orgSlug/purchase/bills/$documentId': typeof Char123LocaleChar125AppOrgSlugShellPurchaseBillsDocumentIdRoute
  '/{-$locale}/$orgSlug/purchase/bills/new': typeof Char123LocaleChar125AppOrgSlugShellPurchaseBillsNewRoute
  '/{-$locale}/$orgSlug/purchase/payments/$documentId': typeof Char123LocaleChar125AppOrgSlugShellPurchasePaymentsDocumentIdRoute
  '/{-$locale}/$orgSlug/purchase/payments/new': typeof Char123LocaleChar125AppOrgSlugShellPurchasePaymentsNewRoute
  '/{-$locale}/$orgSlug/sales/invoices/$documentId': typeof Char123LocaleChar125AppOrgSlugShellSalesInvoicesDocumentIdRoute
  '/{-$locale}/$orgSlug/sales/invoices/new': typeof Char123LocaleChar125AppOrgSlugShellSalesInvoicesNewRoute
  '/{-$locale}/$orgSlug/sales/receipts/$documentId': typeof Char123LocaleChar125AppOrgSlugShellSalesReceiptsDocumentIdRoute
  '/{-$locale}/$orgSlug/sales/receipts/new': typeof Char123LocaleChar125AppOrgSlugShellSalesReceiptsNewRoute
  '/{-$locale}/$orgSlug/purchase/bills': typeof Char123LocaleChar125AppOrgSlugShellPurchaseBillsIndexRoute
  '/{-$locale}/$orgSlug/purchase/payments': typeof Char123LocaleChar125AppOrgSlugShellPurchasePaymentsIndexRoute
  '/{-$locale}/$orgSlug/sales/invoices': typeof Char123LocaleChar125AppOrgSlugShellSalesInvoicesIndexRoute
  '/{-$locale}/$orgSlug/sales/receipts': typeof Char123LocaleChar125AppOrgSlugShellSalesReceiptsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}/_app': typeof Char123LocaleChar125AppRouteRouteWithChildren
  '/{-$locale}/_guest': typeof Char123LocaleChar125GuestRouteRouteWithChildren
  '/{-$locale}/_public': typeof Char123LocaleChar125PublicRouteRouteWithChildren
  '/{-$locale}/_app/$orgSlug': typeof Char123LocaleChar125AppOrgSlugRouteRouteWithChildren
  '/_api/health/live': typeof ApiHealthLiveRoute
  '/{-$locale}/_guest/login': typeof Char123LocaleChar125GuestLoginRoute
  '/{-$locale}/_guest/signup': typeof Char123LocaleChar125GuestSignupRoute
  '/{-$locale}/_public/error': typeof Char123LocaleChar125PublicErrorRoute
  '/{-$locale}/_public/home': typeof Char123LocaleChar125PublicHomeRoute
  '/{-$locale}/_public/playground': typeof Char123LocaleChar125PublicPlaygroundRoute
  '/{-$locale}/_public/privacy-policy': typeof Char123LocaleChar125PublicPrivacyPolicyRoute
  '/{-$locale}/_public/terms-of-service': typeof Char123LocaleChar125PublicTermsOfServiceRoute
  '/{-$locale}/_public/': typeof Char123LocaleChar125PublicIndexRoute
  '/{-$locale}/_app/$orgSlug/_shell': typeof Char123LocaleChar125AppOrgSlugShellRouteRouteWithChildren
  '/{-$locale}/_app/$orgSlug/onboarding': typeof Char123LocaleChar125AppOrgSlugOnboardingRoute
  '/{-$locale}/_app/organizations/new': typeof Char123LocaleChar125AppOrganizationsNewRoute
  '/{-$locale}/_app/$orgSlug/_shell/': typeof Char123LocaleChar125AppOrgSlugShellIndexRoute
  '/{-$locale}/_app/$orgSlug/_shell/accounting/journal-entries': typeof Char123LocaleChar125AppOrgSlugShellAccountingJournalEntriesRoute
  '/{-$locale}/_app/$orgSlug/_shell/records/items': typeof Char123LocaleChar125AppOrgSlugShellRecordsItemsRoute
  '/{-$locale}/_app/$orgSlug/_shell/records/parties': typeof Char123LocaleChar125AppOrgSlugShellRecordsPartiesRoute
  '/{-$locale}/_app/$orgSlug/_shell/reports/general-ledger': typeof Char123LocaleChar125AppOrgSlugShellReportsGeneralLedgerRoute
  '/{-$locale}/_app/$orgSlug/_shell/reports/trial-balance': typeof Char123LocaleChar125AppOrgSlugShellReportsTrialBalanceRoute
  '/{-$locale}/_app/$orgSlug/_shell/settings/accounting-periods': typeof Char123LocaleChar125AppOrgSlugShellSettingsAccountingPeriodsRoute
  '/{-$locale}/_app/$orgSlug/_shell/settings/business': typeof Char123LocaleChar125AppOrgSlugShellSettingsBusinessRoute
  '/{-$locale}/_app/$orgSlug/_shell/settings/chart-of-accounts': typeof Char123LocaleChar125AppOrgSlugShellSettingsChartOfAccountsRoute
  '/{-$locale}/_app/$orgSlug/_shell/purchase/': typeof Char123LocaleChar125AppOrgSlugShellPurchaseIndexRoute
  '/{-$locale}/_app/$orgSlug/_shell/sales/': typeof Char123LocaleChar125AppOrgSlugShellSalesIndexRoute
  '/{-$locale}/_app/$orgSlug/_shell/settings/': typeof Char123LocaleChar125AppOrgSlugShellSettingsIndexRoute
  '/{-$locale}/_app/$orgSlug/_shell/purchase/bills/$documentId': typeof Char123LocaleChar125AppOrgSlugShellPurchaseBillsDocumentIdRoute
  '/{-$locale}/_app/$orgSlug/_shell/purchase/bills/new': typeof Char123LocaleChar125AppOrgSlugShellPurchaseBillsNewRoute
  '/{-$locale}/_app/$orgSlug/_shell/purchase/payments/$documentId': typeof Char123LocaleChar125AppOrgSlugShellPurchasePaymentsDocumentIdRoute
  '/{-$locale}/_app/$orgSlug/_shell/purchase/payments/new': typeof Char123LocaleChar125AppOrgSlugShellPurchasePaymentsNewRoute
  '/{-$locale}/_app/$orgSlug/_shell/sales/invoices/$documentId': typeof Char123LocaleChar125AppOrgSlugShellSalesInvoicesDocumentIdRoute
  '/{-$locale}/_app/$orgSlug/_shell/sales/invoices/new': typeof Char123LocaleChar125AppOrgSlugShellSalesInvoicesNewRoute
  '/{-$locale}/_app/$orgSlug/_shell/sales/receipts/$documentId': typeof Char123LocaleChar125AppOrgSlugShellSalesReceiptsDocumentIdRoute
  '/{-$locale}/_app/$orgSlug/_shell/sales/receipts/new': typeof Char123LocaleChar125AppOrgSlugShellSalesReceiptsNewRoute
  '/{-$locale}/_app/$orgSlug/_shell/purchase/bills/': typeof Char123LocaleChar125AppOrgSlugShellPurchaseBillsIndexRoute
  '/{-$locale}/_app/$orgSlug/_shell/purchase/payments/': typeof Char123LocaleChar125AppOrgSlugShellPurchasePaymentsIndexRoute
  '/{-$locale}/_app/$orgSlug/_shell/sales/invoices/': typeof Char123LocaleChar125AppOrgSlugShellSalesInvoicesIndexRoute
  '/{-$locale}/_app/$orgSlug/_shell/sales/receipts/': typeof Char123LocaleChar125AppOrgSlugShellSalesReceiptsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/{-$locale}/$orgSlug'
    | '/_api/health/live'
    | '/{-$locale}/login'
    | '/{-$locale}/signup'
    | '/{-$locale}/error'
    | '/{-$locale}/home'
    | '/{-$locale}/playground'
    | '/{-$locale}/privacy-policy'
    | '/{-$locale}/terms-of-service'
    | '/{-$locale}/'
    | '/{-$locale}/$orgSlug/onboarding'
    | '/{-$locale}/organizations/new'
    | '/{-$locale}/$orgSlug/'
    | '/{-$locale}/$orgSlug/accounting/journal-entries'
    | '/{-$locale}/$orgSlug/records/items'
    | '/{-$locale}/$orgSlug/records/parties'
    | '/{-$locale}/$orgSlug/reports/general-ledger'
    | '/{-$locale}/$orgSlug/reports/trial-balance'
    | '/{-$locale}/$orgSlug/settings/accounting-periods'
    | '/{-$locale}/$orgSlug/settings/business'
    | '/{-$locale}/$orgSlug/settings/chart-of-accounts'
    | '/{-$locale}/$orgSlug/purchase/'
    | '/{-$locale}/$orgSlug/sales/'
    | '/{-$locale}/$orgSlug/settings/'
    | '/{-$locale}/$orgSlug/purchase/bills/$documentId'
    | '/{-$locale}/$orgSlug/purchase/bills/new'
    | '/{-$locale}/$orgSlug/purchase/payments/$documentId'
    | '/{-$locale}/$orgSlug/purchase/payments/new'
    | '/{-$locale}/$orgSlug/sales/invoices/$documentId'
    | '/{-$locale}/$orgSlug/sales/invoices/new'
    | '/{-$locale}/$orgSlug/sales/receipts/$documentId'
    | '/{-$locale}/$orgSlug/sales/receipts/new'
    | '/{-$locale}/$orgSlug/purchase/bills/'
    | '/{-$locale}/$orgSlug/purchase/payments/'
    | '/{-$locale}/$orgSlug/sales/invoices/'
    | '/{-$locale}/$orgSlug/sales/receipts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$locale}'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/{-$locale}/$orgSlug'
    | '/_api/health/live'
    | '/{-$locale}/login'
    | '/{-$locale}/signup'
    | '/{-$locale}/error'
    | '/{-$locale}/home'
    | '/{-$locale}/playground'
    | '/{-$locale}/privacy-policy'
    | '/{-$locale}/terms-of-service'
    | '/{-$locale}/$orgSlug/onboarding'
    | '/{-$locale}/organizations/new'
    | '/{-$locale}/$orgSlug/accounting/journal-entries'
    | '/{-$locale}/$orgSlug/records/items'
    | '/{-$locale}/$orgSlug/records/parties'
    | '/{-$locale}/$orgSlug/reports/general-ledger'
    | '/{-$locale}/$orgSlug/reports/trial-balance'
    | '/{-$locale}/$orgSlug/settings/accounting-periods'
    | '/{-$locale}/$orgSlug/settings/business'
    | '/{-$locale}/$orgSlug/settings/chart-of-accounts'
    | '/{-$locale}/$orgSlug/purchase'
    | '/{-$locale}/$orgSlug/sales'
    | '/{-$locale}/$orgSlug/settings'
    | '/{-$locale}/$orgSlug/purchase/bills/$documentId'
    | '/{-$locale}/$orgSlug/purchase/bills/new'
    | '/{-$locale}/$orgSlug/purchase/payments/$documentId'
    | '/{-$locale}/$orgSlug/purchase/payments/new'
    | '/{-$locale}/$orgSlug/sales/invoices/$documentId'
    | '/{-$locale}/$orgSlug/sales/invoices/new'
    | '/{-$locale}/$orgSlug/sales/receipts/$documentId'
    | '/{-$locale}/$orgSlug/sales/receipts/new'
    | '/{-$locale}/$orgSlug/purchase/bills'
    | '/{-$locale}/$orgSlug/purchase/payments'
    | '/{-$locale}/$orgSlug/sales/invoices'
    | '/{-$locale}/$orgSlug/sales/receipts'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/{-$locale}/_app'
    | '/{-$locale}/_guest'
    | '/{-$locale}/_public'
    | '/{-$locale}/_app/$orgSlug'
    | '/_api/health/live'
    | '/{-$locale}/_guest/login'
    | '/{-$locale}/_guest/signup'
    | '/{-$locale}/_public/error'
    | '/{-$locale}/_public/home'
    | '/{-$locale}/_public/playground'
    | '/{-$locale}/_public/privacy-policy'
    | '/{-$locale}/_public/terms-of-service'
    | '/{-$locale}/_public/'
    | '/{-$locale}/_app/$orgSlug/_shell'
    | '/{-$locale}/_app/$orgSlug/onboarding'
    | '/{-$locale}/_app/organizations/new'
    | '/{-$locale}/_app/$orgSlug/_shell/'
    | '/{-$locale}/_app/$orgSlug/_shell/accounting/journal-entries'
    | '/{-$locale}/_app/$orgSlug/_shell/records/items'
    | '/{-$locale}/_app/$orgSlug/_shell/records/parties'
    | '/{-$locale}/_app/$orgSlug/_shell/reports/general-ledger'
    | '/{-$locale}/_app/$orgSlug/_shell/reports/trial-balance'
    | '/{-$locale}/_app/$orgSlug/_shell/settings/accounting-periods'
    | '/{-$locale}/_app/$orgSlug/_shell/settings/business'
    | '/{-$locale}/_app/$orgSlug/_shell/settings/chart-of-accounts'
    | '/{-$locale}/_app/$orgSlug/_shell/purchase/'
    | '/{-$locale}/_app/$orgSlug/_shell/sales/'
    | '/{-$locale}/_app/$orgSlug/_shell/settings/'
    | '/{-$locale}/_app/$orgSlug/_shell/purchase/bills/$documentId'
    | '/{-$locale}/_app/$orgSlug/_shell/purchase/bills/new'
    | '/{-$locale}/_app/$orgSlug/_shell/purchase/payments/$documentId'
    | '/{-$locale}/_app/$orgSlug/_shell/purchase/payments/new'
    | '/{-$locale}/_app/$orgSlug/_shell/sales/invoices/$documentId'
    | '/{-$locale}/_app/$orgSlug/_shell/sales/invoices/new'
    | '/{-$locale}/_app/$orgSlug/_shell/sales/receipts/$documentId'
    | '/{-$locale}/_app/$orgSlug/_shell/sales/receipts/new'
    | '/{-$locale}/_app/$orgSlug/_shell/purchase/bills/'
    | '/{-$locale}/_app/$orgSlug/_shell/purchase/payments/'
    | '/{-$locale}/_app/$orgSlug/_shell/sales/invoices/'
    | '/{-$locale}/_app/$orgSlug/_shell/sales/receipts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125RouteRoute: typeof Char123LocaleChar125RouteRouteWithChildren
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiHealthLiveRoute: typeof ApiHealthLiveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/_public': {
      id: '/{-$locale}/_public'
      path: ''
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125PublicRouteRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/_guest': {
      id: '/{-$locale}/_guest'
      path: ''
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125GuestRouteRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/_app': {
      id: '/{-$locale}/_app'
      path: ''
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125AppRouteRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/_public/': {
      id: '/{-$locale}/_public/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125PublicIndexRouteImport
      parentRoute: typeof Char123LocaleChar125PublicRouteRoute
    }
    '/{-$locale}/_public/terms-of-service': {
      id: '/{-$locale}/_public/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/{-$locale}/terms-of-service'
      preLoaderRoute: typeof Char123LocaleChar125PublicTermsOfServiceRouteImport
      parentRoute: typeof Char123LocaleChar125PublicRouteRoute
    }
    '/{-$locale}/_public/privacy-policy': {
      id: '/{-$locale}/_public/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/{-$locale}/privacy-policy'
      preLoaderRoute: typeof Char123LocaleChar125PublicPrivacyPolicyRouteImport
      parentRoute: typeof Char123LocaleChar125PublicRouteRoute
    }
    '/{-$locale}/_public/playground': {
      id: '/{-$locale}/_public/playground'
      path: '/playground'
      fullPath: '/{-$locale}/playground'
      preLoaderRoute: typeof Char123LocaleChar125PublicPlaygroundRouteImport
      parentRoute: typeof Char123LocaleChar125PublicRouteRoute
    }
    '/{-$locale}/_public/home': {
      id: '/{-$locale}/_public/home'
      path: '/home'
      fullPath: '/{-$locale}/home'
      preLoaderRoute: typeof Char123LocaleChar125PublicHomeRouteImport
      parentRoute: typeof Char123LocaleChar125PublicRouteRoute
    }
    '/{-$locale}/_public/error': {
      id: '/{-$locale}/_public/error'
      path: '/error'
      fullPath: '/{-$locale}/error'
      preLoaderRoute: typeof Char123LocaleChar125PublicErrorRouteImport
      parentRoute: typeof Char123LocaleChar125PublicRouteRoute
    }
    '/{-$locale}/_guest/signup': {
      id: '/{-$locale}/_guest/signup'
      path: '/signup'
      fullPath: '/{-$locale}/signup'
      preLoaderRoute: typeof Char123LocaleChar125GuestSignupRouteImport
      parentRoute: typeof Char123LocaleChar125GuestRouteRoute
    }
    '/{-$locale}/_guest/login': {
      id: '/{-$locale}/_guest/login'
      path: '/login'
      fullPath: '/{-$locale}/login'
      preLoaderRoute: typeof Char123LocaleChar125GuestLoginRouteImport
      parentRoute: typeof Char123LocaleChar125GuestRouteRoute
    }
    '/_api/health/live': {
      id: '/_api/health/live'
      path: '/_api/health/live'
      fullPath: '/_api/health/live'
      preLoaderRoute: typeof ApiHealthLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/_app/$orgSlug': {
      id: '/{-$locale}/_app/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/{-$locale}/$orgSlug'
      preLoaderRoute: typeof Char123LocaleChar125AppOrgSlugRouteRouteImport
      parentRoute: typeof Char123LocaleChar125AppRouteRoute
    }
    '/{-$locale}/_app/organizations/new': {
      id: '/{-$locale}/_app/organizations/new'
      path: '/organizations/new'
      fullPath: '/{-$locale}/organizations/new'
      preLoaderRoute: typeof Char123LocaleChar125AppOrganizationsNewRouteImport
      parentRoute: typeof Char123LocaleChar125AppRouteRoute
    }
    '/{-$locale}/_app/$orgSlug/onboarding': {
      id: '/{-$locale}/_app/$orgSlug/onboarding'
      path: '/onboarding'
      fullPath: '/{-$locale}/$orgSlug/onboarding'
      preLoaderRoute: typeof Char123LocaleChar125AppOrgSlugOnboardingRouteImport
      parentRoute: typeof Char123LocaleChar125AppOrgSlugRouteRoute
    }
    '/{-$locale}/_app/$orgSlug/_shell': {
      id: '/{-$locale}/_app/$orgSlug/_shell'
      path: ''
      fullPath: '/{-$locale}/$orgSlug'
      preLoaderRoute: typeof Char123LocaleChar125AppOrgSlugShellRouteRouteImport
      parentRoute: typeof Char123LocaleChar125AppOrgSlugRouteRoute
    }
    '/{-$locale}/_app/$orgSlug/_shell/': {
      id: '/{-$locale}/_app/$orgSlug/_shell/'
      path: '/'
      fullPath: '/{-$locale}/$orgSlug/'
      preLoaderRoute: typeof Char123LocaleChar125AppOrgSlugShellIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AppOrgSlugShellRouteRoute
    }
    '/{-$locale}/_app/$orgSlug/_shell/settings/': {
      id: '/{-$locale}/_app/$orgSlug/_shell/settings/'
      path: '/settings'
      fullPath: '/{-$locale}/$orgSlug/settings/'
      preLoaderRoute: typeof Char123LocaleChar125AppOrgSlugShellSettingsIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AppOrgSlugShellRouteRoute
    }
    '/{-$locale}/_app/$orgSlug/_shell/sales/': {
      id: '/{-$locale}/_app/$orgSlug/_shell/sales/'
      path: '/sales'
      fullPath: '/{-$locale}/$orgSlug/sales/'
      preLoaderRoute: typeof Char123LocaleChar125AppOrgSlugShellSalesIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AppOrgSlugShellRouteRoute
    }
    '/{-$locale}/_app/$orgSlug/_shell/purchase/': {
      id: '/{-$locale}/_app/$orgSlug/_shell/purchase/'
      path: '/purchase'
      fullPath: '/{-$locale}/$orgSlug/purchase/'
      preLoaderRoute: typeof Char123LocaleChar125AppOrgSlugShellPurchaseIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AppOrgSlugShellRouteRoute
    }
    '/{-$locale}/_app/$orgSlug/_shell/settings/chart-of-accounts': {
      id: '/{-$locale}/_app/$orgSlug/_shell/settings/chart-of-accounts'
      path: '/settings/chart-of-accounts'
      fullPath: '/{-$locale}/$orgSlug/settings/chart-of-accounts'
      preLoaderRoute: typeof Char123LocaleChar125AppOrgSlugShellSettingsChartOfAccountsRouteImport
      parentRoute: typeof Char123LocaleChar125AppOrgSlugShellRouteRoute
    }
    '/{-$locale}/_app/$orgSlug/_shell/settings/business': {
      id: '/{-$locale}/_app/$orgSlug/_shell/settings/business'
      path: '/settings/business'
      fullPath: '/{-$locale}/$orgSlug/settings/business'
      preLoaderRoute: typeof Char123LocaleChar125AppOrgSlugShellSettingsBusinessRouteImport
      parentRoute: typeof Char123LocaleChar125AppOrgSlugShellRouteRoute
    }
    '/{-$locale}/_app/$orgSlug/_shell/settings/accounting-periods': {
      id: '/{-$locale}/_app/$orgSlug/_shell/settings/accounting-periods'
      path: '/settings/accounting-periods'
      fullPath: '/{-$locale}/$orgSlug/settings/accounting-periods'
      preLoaderRoute: typeof Char123LocaleChar125AppOrgSlugShellSettingsAccountingPeriodsRouteImport
      parentRoute: typeof Char123LocaleChar125AppOrgSlugShellRouteRoute
    }
    '/{-$locale}/_app/$orgSlug/_shell/reports/trial-balance': {
      id: '/{-$locale}/_app/$orgSlug/_shell/reports/trial-balance'
      path: '/reports/trial-balance'
      fullPath: '/{-$locale}/$orgSlug/reports/trial-balance'
      preLoaderRoute: typeof Char123LocaleChar125AppOrgSlugShellReportsTrialBalanceRouteImport
      parentRoute: typeof Char123LocaleChar125AppOrgSlugShellRouteRoute
    }
    '/{-$locale}/_app/$orgSlug/_shell/reports/general-ledger': {
      id: '/{-$locale}/_app/$orgSlug/_shell/reports/general-ledger'
      path: '/reports/general-ledger'
      fullPath: '/{-$locale}/$orgSlug/reports/general-ledger'
      preLoaderRoute: typeof Char123LocaleChar125AppOrgSlugShellReportsGeneralLedgerRouteImport
      parentRoute: typeof Char123LocaleChar125AppOrgSlugShellRouteRoute
    }
    '/{-$locale}/_app/$orgSlug/_shell/records/parties': {
      id: '/{-$locale}/_app/$orgSlug/_shell/records/parties'
      path: '/records/parties'
      fullPath: '/{-$locale}/$orgSlug/records/parties'
      preLoaderRoute: typeof Char123LocaleChar125AppOrgSlugShellRecordsPartiesRouteImport
      parentRoute: typeof Char123LocaleChar125AppOrgSlugShellRouteRoute
    }
    '/{-$locale}/_app/$orgSlug/_shell/records/items': {
      id: '/{-$locale}/_app/$orgSlug/_shell/records/items'
      path: '/records/items'
      fullPath: '/{-$locale}/$orgSlug/records/items'
      preLoaderRoute: typeof Char123LocaleChar125AppOrgSlugShellRecordsItemsRouteImport
      parentRoute: typeof Char123LocaleChar125AppOrgSlugShellRouteRoute
    }
    '/{-$locale}/_app/$orgSlug/_shell/accounting/journal-entries': {
      id: '/{-$locale}/_app/$orgSlug/_shell/accounting/journal-entries'
      path: '/accounting/journal-entries'
      fullPath: '/{-$locale}/$orgSlug/accounting/journal-entries'
      preLoaderRoute: typeof Char123LocaleChar125AppOrgSlugShellAccountingJournalEntriesRouteImport
      parentRoute: typeof Char123LocaleChar125AppOrgSlugShellRouteRoute
    }
    '/{-$locale}/_app/$orgSlug/_shell/sales/receipts/': {
      id: '/{-$locale}/_app/$orgSlug/_shell/sales/receipts/'
      path: '/sales/receipts'
      fullPath: '/{-$locale}/$orgSlug/sales/receipts/'
      preLoaderRoute: typeof Char123LocaleChar125AppOrgSlugShellSalesReceiptsIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AppOrgSlugShellRouteRoute
    }
    '/{-$locale}/_app/$orgSlug/_shell/sales/invoices/': {
      id: '/{-$locale}/_app/$orgSlug/_shell/sales/invoices/'
      path: '/sales/invoices'
      fullPath: '/{-$locale}/$orgSlug/sales/invoices/'
      preLoaderRoute: typeof Char123LocaleChar125AppOrgSlugShellSalesInvoicesIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AppOrgSlugShellRouteRoute
    }
    '/{-$locale}/_app/$orgSlug/_shell/purchase/payments/': {
      id: '/{-$locale}/_app/$orgSlug/_shell/purchase/payments/'
      path: '/purchase/payments'
      fullPath: '/{-$locale}/$orgSlug/purchase/payments/'
      preLoaderRoute: typeof Char123LocaleChar125AppOrgSlugShellPurchasePaymentsIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AppOrgSlugShellRouteRoute
    }
    '/{-$locale}/_app/$orgSlug/_shell/purchase/bills/': {
      id: '/{-$locale}/_app/$orgSlug/_shell/purchase/bills/'
      path: '/purchase/bills'
      fullPath: '/{-$locale}/$orgSlug/purchase/bills/'
      preLoaderRoute: typeof Char123LocaleChar125AppOrgSlugShellPurchaseBillsIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AppOrgSlugShellRouteRoute
    }
    '/{-$locale}/_app/$orgSlug/_shell/sales/receipts/new': {
      id: '/{-$locale}/_app/$orgSlug/_shell/sales/receipts/new'
      path: '/sales/receipts/new'
      fullPath: '/{-$locale}/$orgSlug/sales/receipts/new'
      preLoaderRoute: typeof Char123LocaleChar125AppOrgSlugShellSalesReceiptsNewRouteImport
      parentRoute: typeof Char123LocaleChar125AppOrgSlugShellRouteRoute
    }
    '/{-$locale}/_app/$orgSlug/_shell/sales/receipts/$documentId': {
      id: '/{-$locale}/_app/$orgSlug/_shell/sales/receipts/$documentId'
      path: '/sales/receipts/$documentId'
      fullPath: '/{-$locale}/$orgSlug/sales/receipts/$documentId'
      preLoaderRoute: typeof Char123LocaleChar125AppOrgSlugShellSalesReceiptsDocumentIdRouteImport
      parentRoute: typeof Char123LocaleChar125AppOrgSlugShellRouteRoute
    }
    '/{-$locale}/_app/$orgSlug/_shell/sales/invoices/new': {
      id: '/{-$locale}/_app/$orgSlug/_shell/sales/invoices/new'
      path: '/sales/invoices/new'
      fullPath: '/{-$locale}/$orgSlug/sales/invoices/new'
      preLoaderRoute: typeof Char123LocaleChar125AppOrgSlugShellSalesInvoicesNewRouteImport
      parentRoute: typeof Char123LocaleChar125AppOrgSlugShellRouteRoute
    }
    '/{-$locale}/_app/$orgSlug/_shell/sales/invoices/$documentId': {
      id: '/{-$locale}/_app/$orgSlug/_shell/sales/invoices/$documentId'
      path: '/sales/invoices/$documentId'
      fullPath: '/{-$locale}/$orgSlug/sales/invoices/$documentId'
      preLoaderRoute: typeof Char123LocaleChar125AppOrgSlugShellSalesInvoicesDocumentIdRouteImport
      parentRoute: typeof Char123LocaleChar125AppOrgSlugShellRouteRoute
    }
    '/{-$locale}/_app/$orgSlug/_shell/purchase/payments/new': {
      id: '/{-$locale}/_app/$orgSlug/_shell/purchase/payments/new'
      path: '/purchase/payments/new'
      fullPath: '/{-$locale}/$orgSlug/purchase/payments/new'
      preLoaderRoute: typeof Char123LocaleChar125AppOrgSlugShellPurchasePaymentsNewRouteImport
      parentRoute: typeof Char123LocaleChar125AppOrgSlugShellRouteRoute
    }
    '/{-$locale}/_app/$orgSlug/_shell/purchase/payments/$documentId': {
      id: '/{-$locale}/_app/$orgSlug/_shell/purchase/payments/$documentId'
      path: '/purchase/payments/$documentId'
      fullPath: '/{-$locale}/$orgSlug/purchase/payments/$documentId'
      preLoaderRoute: typeof Char123LocaleChar125AppOrgSlugShellPurchasePaymentsDocumentIdRouteImport
      parentRoute: typeof Char123LocaleChar125AppOrgSlugShellRouteRoute
    }
    '/{-$locale}/_app/$orgSlug/_shell/purchase/bills/new': {
      id: '/{-$locale}/_app/$orgSlug/_shell/purchase/bills/new'
      path: '/purchase/bills/new'
      fullPath: '/{-$locale}/$orgSlug/purchase/bills/new'
      preLoaderRoute: typeof Char123LocaleChar125AppOrgSlugShellPurchaseBillsNewRouteImport
      parentRoute: typeof Char123LocaleChar125AppOrgSlugShellRouteRoute
    }
    '/{-$locale}/_app/$orgSlug/_shell/purchase/bills/$documentId': {
      id: '/{-$locale}/_app/$orgSlug/_shell/purchase/bills/$documentId'
      path: '/purchase/bills/$documentId'
      fullPath: '/{-$locale}/$orgSlug/purchase/bills/$documentId'
      preLoaderRoute: typeof Char123LocaleChar125AppOrgSlugShellPurchaseBillsDocumentIdRouteImport
      parentRoute: typeof Char123LocaleChar125AppOrgSlugShellRouteRoute
    }
  }
}

interface Char123LocaleChar125AppOrgSlugShellRouteRouteChildren {
  Char123LocaleChar125AppOrgSlugShellIndexRoute: typeof Char123LocaleChar125AppOrgSlugShellIndexRoute
  Char123LocaleChar125AppOrgSlugShellAccountingJournalEntriesRoute: typeof Char123LocaleChar125AppOrgSlugShellAccountingJournalEntriesRoute
  Char123LocaleChar125AppOrgSlugShellRecordsItemsRoute: typeof Char123LocaleChar125AppOrgSlugShellRecordsItemsRoute
  Char123LocaleChar125AppOrgSlugShellRecordsPartiesRoute: typeof Char123LocaleChar125AppOrgSlugShellRecordsPartiesRoute
  Char123LocaleChar125AppOrgSlugShellReportsGeneralLedgerRoute: typeof Char123LocaleChar125AppOrgSlugShellReportsGeneralLedgerRoute
  Char123LocaleChar125AppOrgSlugShellReportsTrialBalanceRoute: typeof Char123LocaleChar125AppOrgSlugShellReportsTrialBalanceRoute
  Char123LocaleChar125AppOrgSlugShellSettingsAccountingPeriodsRoute: typeof Char123LocaleChar125AppOrgSlugShellSettingsAccountingPeriodsRoute
  Char123LocaleChar125AppOrgSlugShellSettingsBusinessRoute: typeof Char123LocaleChar125AppOrgSlugShellSettingsBusinessRoute
  Char123LocaleChar125AppOrgSlugShellSettingsChartOfAccountsRoute: typeof Char123LocaleChar125AppOrgSlugShellSettingsChartOfAccountsRoute
  Char123LocaleChar125AppOrgSlugShellPurchaseIndexRoute: typeof Char123LocaleChar125AppOrgSlugShellPurchaseIndexRoute
  Char123LocaleChar125AppOrgSlugShellSalesIndexRoute: typeof Char123LocaleChar125AppOrgSlugShellSalesIndexRoute
  Char123LocaleChar125AppOrgSlugShellSettingsIndexRoute: typeof Char123LocaleChar125AppOrgSlugShellSettingsIndexRoute
  Char123LocaleChar125AppOrgSlugShellPurchaseBillsDocumentIdRoute: typeof Char123LocaleChar125AppOrgSlugShellPurchaseBillsDocumentIdRoute
  Char123LocaleChar125AppOrgSlugShellPurchaseBillsNewRoute: typeof Char123LocaleChar125AppOrgSlugShellPurchaseBillsNewRoute
  Char123LocaleChar125AppOrgSlugShellPurchasePaymentsDocumentIdRoute: typeof Char123LocaleChar125AppOrgSlugShellPurchasePaymentsDocumentIdRoute
  Char123LocaleChar125AppOrgSlugShellPurchasePaymentsNewRoute: typeof Char123LocaleChar125AppOrgSlugShellPurchasePaymentsNewRoute
  Char123LocaleChar125AppOrgSlugShellSalesInvoicesDocumentIdRoute: typeof Char123LocaleChar125AppOrgSlugShellSalesInvoicesDocumentIdRoute
  Char123LocaleChar125AppOrgSlugShellSalesInvoicesNewRoute: typeof Char123LocaleChar125AppOrgSlugShellSalesInvoicesNewRoute
  Char123LocaleChar125AppOrgSlugShellSalesReceiptsDocumentIdRoute: typeof Char123LocaleChar125AppOrgSlugShellSalesReceiptsDocumentIdRoute
  Char123LocaleChar125AppOrgSlugShellSalesReceiptsNewRoute: typeof Char123LocaleChar125AppOrgSlugShellSalesReceiptsNewRoute
  Char123LocaleChar125AppOrgSlugShellPurchaseBillsIndexRoute: typeof Char123LocaleChar125AppOrgSlugShellPurchaseBillsIndexRoute
  Char123LocaleChar125AppOrgSlugShellPurchasePaymentsIndexRoute: typeof Char123LocaleChar125AppOrgSlugShellPurchasePaymentsIndexRoute
  Char123LocaleChar125AppOrgSlugShellSalesInvoicesIndexRoute: typeof Char123LocaleChar125AppOrgSlugShellSalesInvoicesIndexRoute
  Char123LocaleChar125AppOrgSlugShellSalesReceiptsIndexRoute: typeof Char123LocaleChar125AppOrgSlugShellSalesReceiptsIndexRoute
}

const Char123LocaleChar125AppOrgSlugShellRouteRouteChildren: Char123LocaleChar125AppOrgSlugShellRouteRouteChildren =
  {
    Char123LocaleChar125AppOrgSlugShellIndexRoute:
      Char123LocaleChar125AppOrgSlugShellIndexRoute,
    Char123LocaleChar125AppOrgSlugShellAccountingJournalEntriesRoute:
      Char123LocaleChar125AppOrgSlugShellAccountingJournalEntriesRoute,
    Char123LocaleChar125AppOrgSlugShellRecordsItemsRoute:
      Char123LocaleChar125AppOrgSlugShellRecordsItemsRoute,
    Char123LocaleChar125AppOrgSlugShellRecordsPartiesRoute:
      Char123LocaleChar125AppOrgSlugShellRecordsPartiesRoute,
    Char123LocaleChar125AppOrgSlugShellReportsGeneralLedgerRoute:
      Char123LocaleChar125AppOrgSlugShellReportsGeneralLedgerRoute,
    Char123LocaleChar125AppOrgSlugShellReportsTrialBalanceRoute:
      Char123LocaleChar125AppOrgSlugShellReportsTrialBalanceRoute,
    Char123LocaleChar125AppOrgSlugShellSettingsAccountingPeriodsRoute:
      Char123LocaleChar125AppOrgSlugShellSettingsAccountingPeriodsRoute,
    Char123LocaleChar125AppOrgSlugShellSettingsBusinessRoute:
      Char123LocaleChar125AppOrgSlugShellSettingsBusinessRoute,
    Char123LocaleChar125AppOrgSlugShellSettingsChartOfAccountsRoute:
      Char123LocaleChar125AppOrgSlugShellSettingsChartOfAccountsRoute,
    Char123LocaleChar125AppOrgSlugShellPurchaseIndexRoute:
      Char123LocaleChar125AppOrgSlugShellPurchaseIndexRoute,
    Char123LocaleChar125AppOrgSlugShellSalesIndexRoute:
      Char123LocaleChar125AppOrgSlugShellSalesIndexRoute,
    Char123LocaleChar125AppOrgSlugShellSettingsIndexRoute:
      Char123LocaleChar125AppOrgSlugShellSettingsIndexRoute,
    Char123LocaleChar125AppOrgSlugShellPurchaseBillsDocumentIdRoute:
      Char123LocaleChar125AppOrgSlugShellPurchaseBillsDocumentIdRoute,
    Char123LocaleChar125AppOrgSlugShellPurchaseBillsNewRoute:
      Char123LocaleChar125AppOrgSlugShellPurchaseBillsNewRoute,
    Char123LocaleChar125AppOrgSlugShellPurchasePaymentsDocumentIdRoute:
      Char123LocaleChar125AppOrgSlugShellPurchasePaymentsDocumentIdRoute,
    Char123LocaleChar125AppOrgSlugShellPurchasePaymentsNewRoute:
      Char123LocaleChar125AppOrgSlugShellPurchasePaymentsNewRoute,
    Char123LocaleChar125AppOrgSlugShellSalesInvoicesDocumentIdRoute:
      Char123LocaleChar125AppOrgSlugShellSalesInvoicesDocumentIdRoute,
    Char123LocaleChar125AppOrgSlugShellSalesInvoicesNewRoute:
      Char123LocaleChar125AppOrgSlugShellSalesInvoicesNewRoute,
    Char123LocaleChar125AppOrgSlugShellSalesReceiptsDocumentIdRoute:
      Char123LocaleChar125AppOrgSlugShellSalesReceiptsDocumentIdRoute,
    Char123LocaleChar125AppOrgSlugShellSalesReceiptsNewRoute:
      Char123LocaleChar125AppOrgSlugShellSalesReceiptsNewRoute,
    Char123LocaleChar125AppOrgSlugShellPurchaseBillsIndexRoute:
      Char123LocaleChar125AppOrgSlugShellPurchaseBillsIndexRoute,
    Char123LocaleChar125AppOrgSlugShellPurchasePaymentsIndexRoute:
      Char123LocaleChar125AppOrgSlugShellPurchasePaymentsIndexRoute,
    Char123LocaleChar125AppOrgSlugShellSalesInvoicesIndexRoute:
      Char123LocaleChar125AppOrgSlugShellSalesInvoicesIndexRoute,
    Char123LocaleChar125AppOrgSlugShellSalesReceiptsIndexRoute:
      Char123LocaleChar125AppOrgSlugShellSalesReceiptsIndexRoute,
  }

const Char123LocaleChar125AppOrgSlugShellRouteRouteWithChildren =
  Char123LocaleChar125AppOrgSlugShellRouteRoute._addFileChildren(
    Char123LocaleChar125AppOrgSlugShellRouteRouteChildren,
  )

interface Char123LocaleChar125AppOrgSlugRouteRouteChildren {
  Char123LocaleChar125AppOrgSlugShellRouteRoute: typeof Char123LocaleChar125AppOrgSlugShellRouteRouteWithChildren
  Char123LocaleChar125AppOrgSlugOnboardingRoute: typeof Char123LocaleChar125AppOrgSlugOnboardingRoute
}

const Char123LocaleChar125AppOrgSlugRouteRouteChildren: Char123LocaleChar125AppOrgSlugRouteRouteChildren =
  {
    Char123LocaleChar125AppOrgSlugShellRouteRoute:
      Char123LocaleChar125AppOrgSlugShellRouteRouteWithChildren,
    Char123LocaleChar125AppOrgSlugOnboardingRoute:
      Char123LocaleChar125AppOrgSlugOnboardingRoute,
  }

const Char123LocaleChar125AppOrgSlugRouteRouteWithChildren =
  Char123LocaleChar125AppOrgSlugRouteRoute._addFileChildren(
    Char123LocaleChar125AppOrgSlugRouteRouteChildren,
  )

interface Char123LocaleChar125AppRouteRouteChildren {
  Char123LocaleChar125AppOrgSlugRouteRoute: typeof Char123LocaleChar125AppOrgSlugRouteRouteWithChildren
  Char123LocaleChar125AppOrganizationsNewRoute: typeof Char123LocaleChar125AppOrganizationsNewRoute
}

const Char123LocaleChar125AppRouteRouteChildren: Char123LocaleChar125AppRouteRouteChildren =
  {
    Char123LocaleChar125AppOrgSlugRouteRoute:
      Char123LocaleChar125AppOrgSlugRouteRouteWithChildren,
    Char123LocaleChar125AppOrganizationsNewRoute:
      Char123LocaleChar125AppOrganizationsNewRoute,
  }

const Char123LocaleChar125AppRouteRouteWithChildren =
  Char123LocaleChar125AppRouteRoute._addFileChildren(
    Char123LocaleChar125AppRouteRouteChildren,
  )

interface Char123LocaleChar125GuestRouteRouteChildren {
  Char123LocaleChar125GuestLoginRoute: typeof Char123LocaleChar125GuestLoginRoute
  Char123LocaleChar125GuestSignupRoute: typeof Char123LocaleChar125GuestSignupRoute
}

const Char123LocaleChar125GuestRouteRouteChildren: Char123LocaleChar125GuestRouteRouteChildren =
  {
    Char123LocaleChar125GuestLoginRoute: Char123LocaleChar125GuestLoginRoute,
    Char123LocaleChar125GuestSignupRoute: Char123LocaleChar125GuestSignupRoute,
  }

const Char123LocaleChar125GuestRouteRouteWithChildren =
  Char123LocaleChar125GuestRouteRoute._addFileChildren(
    Char123LocaleChar125GuestRouteRouteChildren,
  )

interface Char123LocaleChar125PublicRouteRouteChildren {
  Char123LocaleChar125PublicErrorRoute: typeof Char123LocaleChar125PublicErrorRoute
  Char123LocaleChar125PublicHomeRoute: typeof Char123LocaleChar125PublicHomeRoute
  Char123LocaleChar125PublicPlaygroundRoute: typeof Char123LocaleChar125PublicPlaygroundRoute
  Char123LocaleChar125PublicPrivacyPolicyRoute: typeof Char123LocaleChar125PublicPrivacyPolicyRoute
  Char123LocaleChar125PublicTermsOfServiceRoute: typeof Char123LocaleChar125PublicTermsOfServiceRoute
  Char123LocaleChar125PublicIndexRoute: typeof Char123LocaleChar125PublicIndexRoute
}

const Char123LocaleChar125PublicRouteRouteChildren: Char123LocaleChar125PublicRouteRouteChildren =
  {
    Char123LocaleChar125PublicErrorRoute: Char123LocaleChar125PublicErrorRoute,
    Char123LocaleChar125PublicHomeRoute: Char123LocaleChar125PublicHomeRoute,
    Char123LocaleChar125PublicPlaygroundRoute:
      Char123LocaleChar125PublicPlaygroundRoute,
    Char123LocaleChar125PublicPrivacyPolicyRoute:
      Char123LocaleChar125PublicPrivacyPolicyRoute,
    Char123LocaleChar125PublicTermsOfServiceRoute:
      Char123LocaleChar125PublicTermsOfServiceRoute,
    Char123LocaleChar125PublicIndexRoute: Char123LocaleChar125PublicIndexRoute,
  }

const Char123LocaleChar125PublicRouteRouteWithChildren =
  Char123LocaleChar125PublicRouteRoute._addFileChildren(
    Char123LocaleChar125PublicRouteRouteChildren,
  )

interface Char123LocaleChar125RouteRouteChildren {
  Char123LocaleChar125AppRouteRoute: typeof Char123LocaleChar125AppRouteRouteWithChildren
  Char123LocaleChar125GuestRouteRoute: typeof Char123LocaleChar125GuestRouteRouteWithChildren
  Char123LocaleChar125PublicRouteRoute: typeof Char123LocaleChar125PublicRouteRouteWithChildren
}

const Char123LocaleChar125RouteRouteChildren: Char123LocaleChar125RouteRouteChildren =
  {
    Char123LocaleChar125AppRouteRoute:
      Char123LocaleChar125AppRouteRouteWithChildren,
    Char123LocaleChar125GuestRouteRoute:
      Char123LocaleChar125GuestRouteRouteWithChildren,
    Char123LocaleChar125PublicRouteRoute:
      Char123LocaleChar125PublicRouteRouteWithChildren,
  }

const Char123LocaleChar125RouteRouteWithChildren =
  Char123LocaleChar125RouteRoute._addFileChildren(
    Char123LocaleChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125RouteRoute: Char123LocaleChar125RouteRouteWithChildren,
  LlmsDottxtRoute: LlmsDottxtRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiHealthLiveRoute: ApiHealthLiveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
